replicaCount: 1

image:
  repository: mongo
  tag: 4.4.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

